<a href="https://colab.research.google.com/github/Chandan-Javali/dem_py/blob/main/t1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
elements = ["jar", "bar", "car", "tar", "mars"]

for i in range(5):  # Iterate 5 times
  element = elements[i]
  print(element)

jar
bar
car
tar
mars


In [ ]:
import numpy as np
b=np.array([1,2,3,4,5])
print(b)



[1 2 3 4 5]


In [ ]:

two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])
two_dimensional_array


array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
two_dimensional_array.shape


(2, 3)

In [ ]:
x=np.zeros((4,5))
print(x)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
y=np.ones((5,6))
print(y)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:

y=np.full((5,6), 1) # Changed from np.ones to np.full with fill_value=1
y


array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [ ]:

import numpy as np
a = np.eye(5)
a


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:

import pandas as pd
import numpy as np

data = {'col1': [1, 2, 3, 4, 5], 'col2': ['a', 'b', 'c', 'd', 'e']}
df = pd.DataFrame(data)
df


col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

In [20]:
import numpy as np
import pandas as pd

data = {
    'name': ['Alice', 'Bob', 'Charlie'],
    'age': [25, 30, 28],
    'city': ['New York', 'London', 'Paris']
}

data


{'name': ['Alice', 'Bob', 'Charlie'],
 'age': [25, 30, 28],
 'city': ['New York', 'London', 'Paris']}

In [21]:

df = pd.DataFrame(data)
df


name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Paris

In [22]:
# prompt: use head, describe, and retrieve age

# Display the first few rows of the DataFrame
print(df.head())

# Generate descriptive statistics
print(df.describe())

# Retrieve the 'age' column
ages = df['age']
ages


      name  age      city
0    Alice   25  New York
1      Bob   30    London
2  Charlie   28     Paris
             age
count   3.000000
mean   27.666667
std     2.516611
min    25.000000
25%    26.500000
50%    28.000000
75%    29.000000
max    30.000000
30
